version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - user_service
      - domain_service
      - audio_service
      - image_service
      - email_service
    networks:
      - app_net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bimbimbambam
      POSTGRES_PASSWORD: bambambimbim
      POSTGRES_DB: app_db
    ports:
      - "8003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:alpine
    ports:
      - "8004:6379"
    networks:
      - app_net

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "8001:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    networks:
      - app_net

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "8002:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "8005:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app_net

  frontend_flutter:
    image: your_flutter_frontend_image
    ports:
      - "8006:80"
    networks:
      - app_net

  auth_service:
    image: your_auth_image
    ports:
      - "8007:8000"
    networks:
      - app_net

  user_service:
    image: your_user_image
    ports:
      - "8008:8000"
    networks:
      - app_net

  domain_service:
    image: your_domain_image
    ports:
      - "8009:8000"
    networks:
      - app_net

  audio_service:
    image: your_audio_image
    ports:
      - "8010:8000"
    networks:
      - app_net

  image_service:
    image: your_image_image
    ports:
      - "8011:8000"
    networks:
      - app_net

  email_service:
    image: your_email_image
    ports:
      - "8012:8000"
    networks:
      - app_net

volumes:
  pgdata:
  minio_data:

networks:
  app_net:
    driver: bridge
