services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - user-service
      - domain-service
      - media-service
    networks:
      - app-net

  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: bimbimbambam
      POSTGRES_PASSWORD: bambambimbim
      POSTGRES_DB: app_db
    ports:
      - "8003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: bimbimbambam
      MINIO_ROOT_PASSWORD: bambambimbim
    ports:
      - "9090:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-net
      
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8007:8000"
    networks:
      - app-net

  user-service:
    build:
      context: ./user-service
    ports:
      - "8008:8000"
    networks:
      - app-net

  domain-service:
    build:
      context: ./domain-service
    ports:
      - "8009:8000"
    networks:
      - app-net
      
  media-service:
    build:
      context: ./media-service
    ports:
      - "8010:8000"
    networks:
      - app-net

volumes:
  pgdata:
  minio_data:

networks:
  app-net:
    driver: bridge
